/*
 * Incident Management API
 * API para la gestión de incidentes, partes de seguros y evidencias.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The AuthRegisterBody model module.
 * @module model/AuthRegisterBody
 * @version 1.0.0
 */
export default class AuthRegisterBody {
  /**
   * Constructs a new <code>AuthRegisterBody</code>.
   * @alias module:model/AuthRegisterBody
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>AuthRegisterBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AuthRegisterBody} obj Optional instance to populate.
   * @return {module:model/AuthRegisterBody} The populated <code>AuthRegisterBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AuthRegisterBody();
      if (data.hasOwnProperty('username'))
        obj.username = ApiClient.convertToType(data['username'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} username
 */
AuthRegisterBody.prototype.username = undefined;

/**
 * @member {String} email
 */
AuthRegisterBody.prototype.email = undefined;

/**
 * @member {String} password
 */
AuthRegisterBody.prototype.password = undefined;

