/*
 * Incident Management API
 * API para la gestión de incidentes, partes de seguros y evidencias.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The Fraude model module.
 * @module model/Fraude
 * @version 1.0.0
 */
export default class Fraude {
  /**
   * Constructs a new <code>Fraude</code>.
   * @alias module:model/Fraude
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Fraude</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Fraude} obj Optional instance to populate.
   * @return {module:model/Fraude} The populated <code>Fraude</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Fraude();
      if (data.hasOwnProperty('list_incidences'))
        obj.listIncidences = ApiClient.convertToType(data['list_incidences'], 'String');
      if (data.hasOwnProperty('incidence_usr'))
        obj.incidenceUsr = ApiClient.convertToType(data['incidence_usr'], 'String');
    }
    return obj;
  }
}

/**
 * Lista de incidencias
 * @member {String} listIncidences
 */
Fraude.prototype.listIncidences = undefined;

/**
 * Incidencia del usuario
 * @member {String} incidenceUsr
 */
Fraude.prototype.incidenceUsr = undefined;

