/*
 * Incident Management API
 * API para la gestión de incidentes, partes de seguros y evidencias.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The Incidencias model module.
 * @module model/Incidencias
 * @version 1.0.0
 */
export default class Incidencias {
  /**
   * Constructs a new <code>Incidencias</code>.
   * @alias module:model/Incidencias
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Incidencias</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Incidencias} obj Optional instance to populate.
   * @return {module:model/Incidencias} The populated <code>Incidencias</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Incidencias();
      if (data.hasOwnProperty('user_nif'))
        obj.userNif = ApiClient.convertToType(data['user_nif'], 'String');
      if (data.hasOwnProperty('file_inf'))
        obj.fileInf = ApiClient.convertToType(data['file_inf'], 'String');
      if (data.hasOwnProperty('type_incidence'))
        obj.typeIncidence = ApiClient.convertToType(data['type_incidence'], 'String');
    }
    return obj;
  }
}

/**
 * Nif de usuario
 * @member {String} userNif
 */
Incidencias.prototype.userNif = undefined;

/**
 * Informe
 * @member {String} fileInf
 */
Incidencias.prototype.fileInf = undefined;

/**
 * Tipo de incidencia
 * @member {String} typeIncidence
 */
Incidencias.prototype.typeIncidence = undefined;

