/*
 * Incident Management API
 * API para la gestión de incidentes, partes de seguros y evidencias.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The IncidentsLocation model module.
 * @module model/IncidentsLocation
 * @version 1.0.0
 */
export default class IncidentsLocation {
  /**
   * Constructs a new <code>IncidentsLocation</code>.
   * @alias module:model/IncidentsLocation
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IncidentsLocation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IncidentsLocation} obj Optional instance to populate.
   * @return {module:model/IncidentsLocation} The populated <code>IncidentsLocation</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IncidentsLocation();
      if (data.hasOwnProperty('latitude'))
        obj.latitude = ApiClient.convertToType(data['latitude'], 'Number');
      if (data.hasOwnProperty('longitude'))
        obj.longitude = ApiClient.convertToType(data['longitude'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} latitude
 */
IncidentsLocation.prototype.latitude = undefined;

/**
 * @member {Number} longitude
 */
IncidentsLocation.prototype.longitude = undefined;

