/*
 * Incident Management API
 * API para la gestión de incidentes, partes de seguros y evidencias.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import IncidentsLocation from './IncidentsLocation';
import IncidentsReportedBy from './IncidentsReportedBy';

/**
 * The IncidentsBody model module.
 * @module model/IncidentsBody
 * @version 1.0.0
 */
export default class IncidentsBody {
  /**
   * Constructs a new <code>IncidentsBody</code>.
   * @alias module:model/IncidentsBody
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IncidentsBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IncidentsBody} obj Optional instance to populate.
   * @return {module:model/IncidentsBody} The populated <code>IncidentsBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IncidentsBody();
      if (data.hasOwnProperty('incident_type'))
        obj.incidentType = ApiClient.convertToType(data['incident_type'], 'String');
      if (data.hasOwnProperty('location'))
        obj.location = IncidentsLocation.constructFromObject(data['location']);
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('reported_by'))
        obj.reportedBy = IncidentsReportedBy.constructFromObject(data['reported_by']);
    }
    return obj;
  }
}

/**
 * @member {String} incidentType
 */
IncidentsBody.prototype.incidentType = undefined;

/**
 * @member {module:model/IncidentsLocation} location
 */
IncidentsBody.prototype.location = undefined;

/**
 * @member {String} description
 */
IncidentsBody.prototype.description = undefined;

/**
 * @member {module:model/IncidentsReportedBy} reportedBy
 */
IncidentsBody.prototype.reportedBy = undefined;

