/*
 * Incident Management API
 * API para la gestión de incidentes, partes de seguros y evidencias.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The IncidentsReportedBy model module.
 * @module model/IncidentsReportedBy
 * @version 1.0.0
 */
export default class IncidentsReportedBy {
  /**
   * Constructs a new <code>IncidentsReportedBy</code>.
   * @alias module:model/IncidentsReportedBy
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IncidentsReportedBy</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IncidentsReportedBy} obj Optional instance to populate.
   * @return {module:model/IncidentsReportedBy} The populated <code>IncidentsReportedBy</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IncidentsReportedBy();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('contact'))
        obj.contact = ApiClient.convertToType(data['contact'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
IncidentsReportedBy.prototype.name = undefined;

/**
 * @member {String} contact
 */
IncidentsReportedBy.prototype.contact = undefined;

