/*
 * Incident Management API
 * API para la gestión de incidentes, partes de seguros y evidencias.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The Indemnizacion model module.
 * @module model/Indemnizacion
 * @version 1.0.0
 */
export default class Indemnizacion {
  /**
   * Constructs a new <code>Indemnizacion</code>.
   * @alias module:model/Indemnizacion
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Indemnizacion</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Indemnizacion} obj Optional instance to populate.
   * @return {module:model/Indemnizacion} The populated <code>Indemnizacion</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Indemnizacion();
      if (data.hasOwnProperty('ok'))
        obj.ok = ApiClient.convertToType(data['ok'], 'Boolean');
      if (data.hasOwnProperty('suma'))
        obj.suma = ApiClient.convertToType(data['suma'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Boolean} ok
 */
Indemnizacion.prototype.ok = undefined;

/**
 * @member {Number} suma
 */
Indemnizacion.prototype.suma = undefined;

