/*
 * Incident Management API
 * API para la gestión de incidentes, partes de seguros y evidencias.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The InlineResponse2001PolicyDetails model module.
 * @module model/InlineResponse2001PolicyDetails
 * @version 1.0.0
 */
export default class InlineResponse2001PolicyDetails {
  /**
   * Constructs a new <code>InlineResponse2001PolicyDetails</code>.
   * @alias module:model/InlineResponse2001PolicyDetails
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse2001PolicyDetails</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2001PolicyDetails} obj Optional instance to populate.
   * @return {module:model/InlineResponse2001PolicyDetails} The populated <code>InlineResponse2001PolicyDetails</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse2001PolicyDetails();
      if (data.hasOwnProperty('holder_name'))
        obj.holderName = ApiClient.convertToType(data['holder_name'], 'String');
      if (data.hasOwnProperty('coverage'))
        obj.coverage = ApiClient.convertToType(data['coverage'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} holderName
 */
InlineResponse2001PolicyDetails.prototype.holderName = undefined;

/**
 * @member {String} coverage
 */
InlineResponse2001PolicyDetails.prototype.coverage = undefined;

