/*
 * Incident Management API
 * API para la gestión de incidentes, partes de seguros y evidencias.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The InsuranceClaimBody model module.
 * @module model/InsuranceClaimBody
 * @version 1.0.0
 */
export default class InsuranceClaimBody {
  /**
   * Constructs a new <code>InsuranceClaimBody</code>.
   * @alias module:model/InsuranceClaimBody
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InsuranceClaimBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InsuranceClaimBody} obj Optional instance to populate.
   * @return {module:model/InsuranceClaimBody} The populated <code>InsuranceClaimBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InsuranceClaimBody();
      if (data.hasOwnProperty('incident_id'))
        obj.incidentId = ApiClient.convertToType(data['incident_id'], 'String');
      if (data.hasOwnProperty('insured_name'))
        obj.insuredName = ApiClient.convertToType(data['insured_name'], 'String');
      if (data.hasOwnProperty('policy_number'))
        obj.policyNumber = ApiClient.convertToType(data['policy_number'], 'String');
      if (data.hasOwnProperty('damage_description'))
        obj.damageDescription = ApiClient.convertToType(data['damage_description'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} incidentId
 */
InsuranceClaimBody.prototype.incidentId = undefined;

/**
 * @member {String} insuredName
 */
InsuranceClaimBody.prototype.insuredName = undefined;

/**
 * @member {String} policyNumber
 */
InsuranceClaimBody.prototype.policyNumber = undefined;

/**
 * @member {String} damageDescription
 */
InsuranceClaimBody.prototype.damageDescription = undefined;

