/*
 * Incident Management API
 * API para la gestión de incidentes, partes de seguros y evidencias.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The ListaInc model module.
 * @module model/ListaInc
 * @version 1.0.0
 */
export default class ListaInc {
  /**
   * Constructs a new <code>ListaInc</code>.
   * @alias module:model/ListaInc
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ListaInc</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ListaInc} obj Optional instance to populate.
   * @return {module:model/ListaInc} The populated <code>ListaInc</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ListaInc();
      if (data.hasOwnProperty('lista_Inc'))
        obj.listaInc = ApiClient.convertToType(data['lista_Inc'], 'String');
    }
    return obj;
  }
}

/**
 * Lista de incidencias
 * @member {String} listaInc
 */
ListaInc.prototype.listaInc = undefined;

