/*
 * Incident Management API
 * API para la gestión de incidentes, partes de seguros y evidencias.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The Poliza model module.
 * @module model/Poliza
 * @version 1.0.0
 */
export default class Poliza {
  /**
   * Constructs a new <code>Poliza</code>.
   * @alias module:model/Poliza
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Poliza</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Poliza} obj Optional instance to populate.
   * @return {module:model/Poliza} The populated <code>Poliza</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Poliza();
      if (data.hasOwnProperty('nombre'))
        obj.nombre = ApiClient.convertToType(data['nombre'], 'String');
      if (data.hasOwnProperty('direccion'))
        obj.direccion = ApiClient.convertToType(data['direccion'], 'String');
      if (data.hasOwnProperty('fecha_inicio'))
        obj.fechaInicio = ApiClient.convertToType(data['fecha_inicio'], 'Date');
      if (data.hasOwnProperty('fecha_fin'))
        obj.fechaFin = ApiClient.convertToType(data['fecha_fin'], 'Date');
      if (data.hasOwnProperty('precio'))
        obj.precio = ApiClient.convertToType(data['precio'], 'Number');
      if (data.hasOwnProperty('deducible'))
        obj.deducible = ApiClient.convertToType(data['deducible'], 'Number');
    }
    return obj;
  }
}

/**
 * Nombre del cliente
 * @member {String} nombre
 */
Poliza.prototype.nombre = undefined;

/**
 * Dirección del cliente
 * @member {String} direccion
 */
Poliza.prototype.direccion = undefined;

/**
 * Fecha de inicio de la Póliza
 * @member {Date} fechaInicio
 */
Poliza.prototype.fechaInicio = undefined;

/**
 * Fecha de término de la Póliza
 * @member {Date} fechaFin
 */
Poliza.prototype.fechaFin = undefined;

/**
 * Precio del seguro
 * @member {Number} precio
 */
Poliza.prototype.precio = undefined;

/**
 * Precio a pagar en caso de siniestro
 * @member {Number} deducible
 */
Poliza.prototype.deducible = undefined;

