/*
 * Incident Management API
 * API para la gestión de incidentes, partes de seguros y evidencias.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The Reclamacion model module.
 * @module model/Reclamacion
 * @version 1.0.0
 */
export default class Reclamacion {
  /**
   * Constructs a new <code>Reclamacion</code>.
   * @alias module:model/Reclamacion
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Reclamacion</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Reclamacion} obj Optional instance to populate.
   * @return {module:model/Reclamacion} The populated <code>Reclamacion</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Reclamacion();
      if (data.hasOwnProperty('ok'))
        obj.ok = ApiClient.convertToType(data['ok'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {Boolean} ok
 */
Reclamacion.prototype.ok = undefined;

