/*
 * Incident Management API
 * API para la gestión de incidentes, partes de seguros y evidencias.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The Seguro model module.
 * @module model/Seguro
 * @version 1.0.0
 */
export default class Seguro {
  /**
   * Constructs a new <code>Seguro</code>.
   * @alias module:model/Seguro
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Seguro</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Seguro} obj Optional instance to populate.
   * @return {module:model/Seguro} The populated <code>Seguro</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Seguro();
      if (data.hasOwnProperty('cliente'))
        obj.cliente = ApiClient.convertToType(data['cliente'], 'String');
      if (data.hasOwnProperty('tipo'))
        obj.tipo = ApiClient.convertToType(data['tipo'], 'String');
      if (data.hasOwnProperty('precio'))
        obj.precio = ApiClient.convertToType(data['precio'], 'Number');
    }
    return obj;
  }
}

/**
 * El cliente que quiere el seguro
 * @member {String} cliente
 */
Seguro.prototype.cliente = undefined;

/**
 * Tipo de seguro que quiere
 * @member {String} tipo
 */
Seguro.prototype.tipo = undefined;

/**
 * Precio del seguro
 * @member {Number} precio
 */
Seguro.prototype.precio = undefined;

