/*
 * Incident Management API
 * API para la gestión de incidentes, partes de seguros y evidencias.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The Usuario model module.
 * @module model/Usuario
 * @version 1.0.0
 */
export default class Usuario {
  /**
   * Constructs a new <code>Usuario</code>.
   * @alias module:model/Usuario
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Usuario</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Usuario} obj Optional instance to populate.
   * @return {module:model/Usuario} The populated <code>Usuario</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Usuario();
      if (data.hasOwnProperty('user_nif'))
        obj.userNif = ApiClient.convertToType(data['user_nif'], 'String');
    }
    return obj;
  }
}

/**
 * Nif de usuario
 * @member {String} userNif
 */
Usuario.prototype.userNif = undefined;

