/*
 * Incident Management API
 * API para la gestión de incidentes, partes de seguros y evidencias.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";

/**
* Fraude service.
* @module api/FraudeApi
* @version 1.0.0
*/
export default class FraudeApi {

    /**
    * Constructs a new FraudeApi. 
    * @alias module:api/FraudeApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the fraudListIncidencesIncidenceUsrGet operation.
     * @callback moduleapi/FraudeApi~fraudListIncidencesIncidenceUsrGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Consultar posible fraude
     * Consultar posible fraude
     * @param {String} listIncidences 
     * @param {String} incidenceUsr 
     * @param {module:api/FraudeApi~fraudListIncidencesIncidenceUsrGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    fraudListIncidencesIncidenceUsrGet(listIncidences, incidenceUsr, callback) {
      
      let postBody = null;
      // verify the required parameter 'listIncidences' is set
      if (listIncidences === undefined || listIncidences === null) {
        throw new Error("Missing the required parameter 'listIncidences' when calling fraudListIncidencesIncidenceUsrGet");
      }
      // verify the required parameter 'incidenceUsr' is set
      if (incidenceUsr === undefined || incidenceUsr === null) {
        throw new Error("Missing the required parameter 'incidenceUsr' when calling fraudListIncidencesIncidenceUsrGet");
      }

      let pathParams = {
        'list_incidences': listIncidences,'incidence_usr': incidenceUsr
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/fraud/{list_incidences}/{incidence_usr}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}