/*
 * Incident Management API
 * API para la gestión de incidentes, partes de seguros y evidencias.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import Indemnizacion from '../model/Indemnizacion';

/**
* Indemnizacion service.
* @module api/IndemnizacionApi
* @version 1.0.0
*/
export default class IndemnizacionApi {

    /**
    * Constructs a new IndemnizacionApi. 
    * @alias module:api/IndemnizacionApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the indemnizacionClienteIdGet operation.
     * @callback moduleapi/IndemnizacionApi~indemnizacionClienteIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Indemnizacion{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Consulta la cantidad a percibir por el usuario
     * @param {String} cliente 
     * @param {Number} id 
     * @param {module:api/IndemnizacionApi~indemnizacionClienteIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    indemnizacionClienteIdGet(cliente, id, callback) {
      
      let postBody = null;
      // verify the required parameter 'cliente' is set
      if (cliente === undefined || cliente === null) {
        throw new Error("Missing the required parameter 'cliente' when calling indemnizacionClienteIdGet");
      }
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling indemnizacionClienteIdGet");
      }

      let pathParams = {
        'cliente': cliente,'id': id
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Indemnizacion;

      return this.apiClient.callApi(
        '/indemnizacion/{cliente}/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}