/*
 * Incident Management API
 * API para la gestión de incidentes, partes de seguros y evidencias.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";

/**
* Notificar service.
* @module api/NotificarApi
* @version 1.0.0
*/
export default class NotificarApi {

    /**
    * Constructs a new NotificarApi. 
    * @alias module:api/NotificarApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the notificarIdUsuarioPut operation.
     * @callback moduleapi/NotificarApi~notificarIdUsuarioPutCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Notifica al usuario la resolucion
     * @param {String} idUsuario 
     * @param {module:api/NotificarApi~notificarIdUsuarioPutCallback} callback The callback function, accepting three arguments: error, data, response
     */
    notificarIdUsuarioPut(idUsuario, callback) {
      
      let postBody = null;
      // verify the required parameter 'idUsuario' is set
      if (idUsuario === undefined || idUsuario === null) {
        throw new Error("Missing the required parameter 'idUsuario' when calling notificarIdUsuarioPut");
      }

      let pathParams = {
        'id_usuario': idUsuario
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/notificar/{id_usuario}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}