/*
 * Incident Management API
 * API para la gestión de incidentes, partes de seguros y evidencias.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";

/**
* Usuario service.
* @module api/UsuarioApi
* @version 1.0.0
*/
export default class UsuarioApi {

    /**
    * Constructs a new UsuarioApi. 
    * @alias module:api/UsuarioApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the userValidateuserNifGet operation.
     * @callback moduleapi/UsuarioApi~userValidateuserNifGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Validacion de usuario
     * Validacion de usuario
     * @param {String} userNif 
     * @param {module:api/UsuarioApi~userValidateuserNifGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    userValidateuserNifGet(userNif, callback) {
      
      let postBody = null;
      // verify the required parameter 'userNif' is set
      if (userNif === undefined || userNif === null) {
        throw new Error("Missing the required parameter 'userNif' when calling userValidateuserNifGet");
      }

      let pathParams = {
        'user_nif': userNif
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/user/validate{user_nif}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}