/*
 * Incident Management API
 * API para la gestión de incidentes, partes de seguros y evidencias.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.IncidentManagementApi);
  }
}(this, function(expect, IncidentManagementApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('EvidenceUploadBody', function() {
      beforeEach(function() {
        instance = new IncidentManagementApi.EvidenceUploadBody();
      });

      it('should create an instance of EvidenceUploadBody', function() {
        // TODO: update the code to test EvidenceUploadBody
        expect(instance).to.be.a(IncidentManagementApi.EvidenceUploadBody);
      });

      it('should have the property claimId (base name: "claim_id")', function() {
        // TODO: update the code to test the property claimId
        expect(instance).to.have.property('claimId');
        // expect(instance.claimId).to.be(expectedValueLiteral);
      });

      it('should have the property file (base name: "file")', function() {
        // TODO: update the code to test the property file
        expect(instance).to.have.property('file');
        // expect(instance.file).to.be(expectedValueLiteral);
      });

    });
  });

}));
