/*
 * Incident Management API
 * API para la gestión de incidentes, partes de seguros y evidencias.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.IncidentManagementApi);
  }
}(this, function(expect, IncidentManagementApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Incidencias', function() {
      beforeEach(function() {
        instance = new IncidentManagementApi.Incidencias();
      });

      it('should create an instance of Incidencias', function() {
        // TODO: update the code to test Incidencias
        expect(instance).to.be.a(IncidentManagementApi.Incidencias);
      });

      it('should have the property userNif (base name: "user_nif")', function() {
        // TODO: update the code to test the property userNif
        expect(instance).to.have.property('userNif');
        // expect(instance.userNif).to.be(expectedValueLiteral);
      });

      it('should have the property fileInf (base name: "file_inf")', function() {
        // TODO: update the code to test the property fileInf
        expect(instance).to.have.property('fileInf');
        // expect(instance.fileInf).to.be(expectedValueLiteral);
      });

      it('should have the property typeIncidence (base name: "type_incidence")', function() {
        // TODO: update the code to test the property typeIncidence
        expect(instance).to.have.property('typeIncidence');
        // expect(instance.typeIncidence).to.be(expectedValueLiteral);
      });

    });
  });

}));
