/*
 * Incident Management API
 * API para la gestión de incidentes, partes de seguros y evidencias.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.IncidentManagementApi);
  }
}(this, function(expect, IncidentManagementApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('IncidentsBody', function() {
      beforeEach(function() {
        instance = new IncidentManagementApi.IncidentsBody();
      });

      it('should create an instance of IncidentsBody', function() {
        // TODO: update the code to test IncidentsBody
        expect(instance).to.be.a(IncidentManagementApi.IncidentsBody);
      });

      it('should have the property incidentType (base name: "incident_type")', function() {
        // TODO: update the code to test the property incidentType
        expect(instance).to.have.property('incidentType');
        // expect(instance.incidentType).to.be(expectedValueLiteral);
      });

      it('should have the property location (base name: "location")', function() {
        // TODO: update the code to test the property location
        expect(instance).to.have.property('location');
        // expect(instance.location).to.be(expectedValueLiteral);
      });

      it('should have the property description (base name: "description")', function() {
        // TODO: update the code to test the property description
        expect(instance).to.have.property('description');
        // expect(instance.description).to.be(expectedValueLiteral);
      });

      it('should have the property reportedBy (base name: "reported_by")', function() {
        // TODO: update the code to test the property reportedBy
        expect(instance).to.have.property('reportedBy');
        // expect(instance.reportedBy).to.be(expectedValueLiteral);
      });

    });
  });

}));
