/*
 * Incident Management API
 * API para la gestión de incidentes, partes de seguros y evidencias.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.IncidentManagementApi);
  }
}(this, function(expect, IncidentManagementApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Indemnizacion', function() {
      beforeEach(function() {
        instance = new IncidentManagementApi.Indemnizacion();
      });

      it('should create an instance of Indemnizacion', function() {
        // TODO: update the code to test Indemnizacion
        expect(instance).to.be.a(IncidentManagementApi.Indemnizacion);
      });

      it('should have the property ok (base name: "ok")', function() {
        // TODO: update the code to test the property ok
        expect(instance).to.have.property('ok');
        // expect(instance.ok).to.be(expectedValueLiteral);
      });

      it('should have the property suma (base name: "suma")', function() {
        // TODO: update the code to test the property suma
        expect(instance).to.have.property('suma');
        // expect(instance.suma).to.be(expectedValueLiteral);
      });

    });
  });

}));
