/*
 * Incident Management API
 * API para la gestión de incidentes, partes de seguros y evidencias.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.IncidentManagementApi);
  }
}(this, function(expect, IncidentManagementApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('InsuranceClaimBody', function() {
      beforeEach(function() {
        instance = new IncidentManagementApi.InsuranceClaimBody();
      });

      it('should create an instance of InsuranceClaimBody', function() {
        // TODO: update the code to test InsuranceClaimBody
        expect(instance).to.be.a(IncidentManagementApi.InsuranceClaimBody);
      });

      it('should have the property incidentId (base name: "incident_id")', function() {
        // TODO: update the code to test the property incidentId
        expect(instance).to.have.property('incidentId');
        // expect(instance.incidentId).to.be(expectedValueLiteral);
      });

      it('should have the property insuredName (base name: "insured_name")', function() {
        // TODO: update the code to test the property insuredName
        expect(instance).to.have.property('insuredName');
        // expect(instance.insuredName).to.be(expectedValueLiteral);
      });

      it('should have the property policyNumber (base name: "policy_number")', function() {
        // TODO: update the code to test the property policyNumber
        expect(instance).to.have.property('policyNumber');
        // expect(instance.policyNumber).to.be(expectedValueLiteral);
      });

      it('should have the property damageDescription (base name: "damage_description")', function() {
        // TODO: update the code to test the property damageDescription
        expect(instance).to.have.property('damageDescription');
        // expect(instance.damageDescription).to.be(expectedValueLiteral);
      });

    });
  });

}));
