/*
 * Incident Management API
 * API para la gestión de incidentes, partes de seguros y evidencias.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.IncidentManagementApi);
  }
}(this, function(expect, IncidentManagementApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Poliza', function() {
      beforeEach(function() {
        instance = new IncidentManagementApi.Poliza();
      });

      it('should create an instance of Poliza', function() {
        // TODO: update the code to test Poliza
        expect(instance).to.be.a(IncidentManagementApi.Poliza);
      });

      it('should have the property nombre (base name: "nombre")', function() {
        // TODO: update the code to test the property nombre
        expect(instance).to.have.property('nombre');
        // expect(instance.nombre).to.be(expectedValueLiteral);
      });

      it('should have the property direccion (base name: "direccion")', function() {
        // TODO: update the code to test the property direccion
        expect(instance).to.have.property('direccion');
        // expect(instance.direccion).to.be(expectedValueLiteral);
      });

      it('should have the property fechaInicio (base name: "fecha_inicio")', function() {
        // TODO: update the code to test the property fechaInicio
        expect(instance).to.have.property('fechaInicio');
        // expect(instance.fechaInicio).to.be(expectedValueLiteral);
      });

      it('should have the property fechaFin (base name: "fecha_fin")', function() {
        // TODO: update the code to test the property fechaFin
        expect(instance).to.have.property('fechaFin');
        // expect(instance.fechaFin).to.be(expectedValueLiteral);
      });

      it('should have the property precio (base name: "precio")', function() {
        // TODO: update the code to test the property precio
        expect(instance).to.have.property('precio');
        // expect(instance.precio).to.be(expectedValueLiteral);
      });

      it('should have the property deducible (base name: "deducible")', function() {
        // TODO: update the code to test the property deducible
        expect(instance).to.have.property('deducible');
        // expect(instance.deducible).to.be(expectedValueLiteral);
      });

    });
  });

}));
