/*
 * Incident Management API
 * API para la gestión de incidentes, partes de seguros y evidencias.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.IncidentManagementApi);
  }
}(this, function(expect, IncidentManagementApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Seguro', function() {
      beforeEach(function() {
        instance = new IncidentManagementApi.Seguro();
      });

      it('should create an instance of Seguro', function() {
        // TODO: update the code to test Seguro
        expect(instance).to.be.a(IncidentManagementApi.Seguro);
      });

      it('should have the property cliente (base name: "cliente")', function() {
        // TODO: update the code to test the property cliente
        expect(instance).to.have.property('cliente');
        // expect(instance.cliente).to.be(expectedValueLiteral);
      });

      it('should have the property tipo (base name: "tipo")', function() {
        // TODO: update the code to test the property tipo
        expect(instance).to.have.property('tipo');
        // expect(instance.tipo).to.be(expectedValueLiteral);
      });

      it('should have the property precio (base name: "precio")', function() {
        // TODO: update the code to test the property precio
        expect(instance).to.have.property('precio');
        // expect(instance.precio).to.be(expectedValueLiteral);
      });

    });
  });

}));
