/*
 * Incident Management API
 * API para la gestión de incidentes, partes de seguros y evidencias.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.IncidentManagementApi);
  }
}(this, function(expect, IncidentManagementApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new IncidentManagementApi.FraudeApi();
  });

  describe('(package)', function() {
    describe('FraudeApi', function() {
      describe('fraudListIncidencesIncidenceUsrGet', function() {
        it('should call fraudListIncidencesIncidenceUsrGet successfully', function(done) {
          // TODO: uncomment, update parameter values for fraudListIncidencesIncidenceUsrGet call
          /*

          instance.fraudListIncidencesIncidenceUsrGet(listIncidences, incidenceUsr, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
