/*
 * Incident Management API
 * API para la gestión de incidentes, partes de seguros y evidencias.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.IncidentManagementApi);
  }
}(this, function(expect, IncidentManagementApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new IncidentManagementApi.IncidenteApi();
  });

  describe('(package)', function() {
    describe('IncidenteApi', function() {
      describe('incidentsPost', function() {
        it('should call incidentsPost successfully', function(done) {
          // TODO: uncomment, update parameter values for incidentsPost call and complete the assertions
          /*

          instance.incidentsPost(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(IncidentManagementApi.InlineResponse201);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('insuranceClaimPost', function() {
        it('should call insuranceClaimPost successfully', function(done) {
          // TODO: uncomment, update parameter values for insuranceClaimPost call and complete the assertions
          /*

          instance.insuranceClaimPost(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(IncidentManagementApi.InlineResponse2011);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('insurancePolicyValidatePost', function() {
        it('should call insurancePolicyValidatePost successfully', function(done) {
          // TODO: uncomment, update parameter values for insurancePolicyValidatePost call and complete the assertions
          /*

          instance.insurancePolicyValidatePost(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(IncidentManagementApi.InlineResponse2001);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
