/*
 * Incident Management API
 * API para la gestión de incidentes, partes de seguros y evidencias.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.IncidentManagementApi);
  }
}(this, function(expect, IncidentManagementApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new IncidentManagementApi.PolizaApi();
  });

  describe('(package)', function() {
    describe('PolizaApi', function() {
      describe('polizaClienteGet', function() {
        it('should call polizaClienteGet successfully', function(done) {
          // TODO: uncomment, update parameter values for polizaClienteGet call and complete the assertions
          /*

          instance.polizaClienteGet(cliente, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(IncidentManagementApi.Poliza);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('polizaClienteIdGet', function() {
        it('should call polizaClienteIdGet successfully', function(done) {
          // TODO: uncomment, update parameter values for polizaClienteIdGet call and complete the assertions
          /*

          instance.polizaClienteIdGet(cliente, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(IncidentManagementApi.Poliza);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('polizaClientePost', function() {
        it('should call polizaClientePost successfully', function(done) {
          // TODO: uncomment, update parameter values for polizaClientePost call and complete the assertions
          /*

          instance.polizaClientePost(cliente, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(IncidentManagementApi.Poliza);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('polizaPost', function() {
        it('should call polizaPost successfully', function(done) {
          // TODO: uncomment, update parameter values for polizaPost call and complete the assertions
          /*

          instance.polizaPost(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(IncidentManagementApi.Poliza);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
