/*
 * Incident Management API
 * API para la gestión de incidentes, partes de seguros y evidencias.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.IncidentManagementApi);
  }
}(this, function(expect, IncidentManagementApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new IncidentManagementApi.SegurosApi();
  });

  describe('(package)', function() {
    describe('SegurosApi', function() {
      describe('seguroClienteGet', function() {
        it('should call seguroClienteGet successfully', function(done) {
          // TODO: uncomment, update parameter values for seguroClienteGet call and complete the assertions
          /*

          instance.seguroClienteGet(cliente, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(IncidentManagementApi.Seguro);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('seguroClienteIdGet', function() {
        it('should call seguroClienteIdGet successfully', function(done) {
          // TODO: uncomment, update parameter values for seguroClienteIdGet call and complete the assertions
          /*

          instance.seguroClienteIdGet(cliente, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(IncidentManagementApi.Seguro);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('seguroClienteIdPut', function() {
        it('should call seguroClienteIdPut successfully', function(done) {
          // TODO: uncomment, update parameter values for seguroClienteIdPut call and complete the assertions
          /*

          instance.seguroClienteIdPut(body, cliente, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(IncidentManagementApi.Seguro);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('seguroPost', function() {
        it('should call seguroPost successfully', function(done) {
          // TODO: uncomment, update parameter values for seguroPost call and complete the assertions
          /*

          instance.seguroPost(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(IncidentManagementApi.Seguro);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('seguroPrecioPost', function() {
        it('should call seguroPrecioPost successfully', function(done) {
          // TODO: uncomment, update parameter values for seguroPrecioPost call and complete the assertions
          /*

          instance.seguroPrecioPost(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(IncidentManagementApi.Seguro);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
